services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'Password1234'
      MYSQL_DATABASE: 'db'
    volumes:
      - ./database_students.sql:/docker-entrypoint-initdb.d/database_students.sql
    ports:
      - "3306:3306"

  pythonapp:
    build: .
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
